name: Build CME Docker Image

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker Image and Publish to Github Packages
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_TOKEN }}
          registry: docker.pkg.github.com
          image_name: crackmapexec